development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: mysql
  database: rafflr_test
  username: rafflr
  password: rafflr
  host: localhost

production:
  adapter: mysql
  database: rafflr
  username: rafflr
  password: xxxxxx
  host: mysql.rafflr.com

